tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "jesseduffield/lazydocker"

brew "mas"
brew "bats-core"
brew "sqlite"
brew "python"
brew "ansible"
brew "libffi"
brew "colordiff"
brew "git"
brew "git-secrets"
brew "gnu-sed"
brew "gawk"
brew "graphviz"
brew "iperf3"
brew "lrzsz"
brew "nkf"
brew "nodebrew"
brew "p7zip"
brew "tree"
brew "pass"
brew "pipenv"
brew "rbenv"
brew "rbenv-communal-gems"
brew "reattach-to-user-namespace"
brew "rsync"
brew "screen"
brew "shellcheck"
brew "sshfs"
brew "tcptraceroute"
brew "telnet"
brew "terraform"
brew "tmux"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "jesseduffield/lazydocker/lazydocker"

cask "bitwarden"
cask "osxfuse"
cask "docker"
#cask "google-cloud-sdk"
cask "gpg-suite"
cask "java"
cask "the-unarchiver"
cask "vagrant"
cask "wireshark"
cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/versions/iterm2"

mas "LINE", id: 539883307

